### PR TITLE
UI changes;

### PR DESCRIPTION
**Pull request by hkAlice**
Reworking the UI a little bit (need to get rid of old stuff)

sapphirebootwpf_2017-10-12_20-25-14

Moving forwards:
* Need to work on the settings page still, and remove our old assets.

### CODE REVIEW

**Comment by NotAdam** [comment]
tbh I don't get why the UI is being reworked while still using WebBrowser

it'd be pretty simple to just move it over and do the whole UI in WPF and it's not going to need a million images to achieve the same thing

**Comment by goaaats** [comment]
We had the whole UI built in WPF before, it just used all square assets and we got problems on that front recently. Should be given some thought, main point was to give server owners more customization abilities.

**Comment by NotAdam** [comment]
ah okay, that makes sense then

In that case, would be worthwhile either using libcef or using something like electron and saving a lot of effort and getting decent rendering at the same time

**Comment by zynjec** [comment]
The Chromium Embedded Framework would make the launcher a couple hundred megs, a little overkill.

I think the end goal, is to allow developers/server operators design their own launchers as they see fit since it's a very simple RESTful login flow. For example, I've designed one that is completely void of any webpage at all.

**Comment by NotAdam** [comment]
No idea where you get that figure from, libcef is like ~26mb or so compressed and it's almost trivial to implement, electron on the other hand is probably double that at least.

Sure, people can make their own launchers, it's not all that hard but people are just going to be opting for a web based approach given how things are currently implemented unless the approach is changed down the line - makes sense to use something proper that isn't clunky to make changes to

**Comment by SapphireMordred** [comment]
Let me jump in here aswell. I am all for a better support for modern css etc. I know little about available web controls in c#, if there is something better that does not include major overhead, it would certainly be worth investigating.
Going back to the launcher being stand alone is somthing i am not too keen of as customizability is the main reason it is what it is now.

**Comment by SapphireMordred** [comment]
For whatever reasons i thought this one was merged already. You'll have to resolve the conflicts.

**Pull request merged**
